### ISSUE TITLE
org.yaml.snakeyaml.error.YAMLException: Number of aliases for non-scalar nodes exceeds the specified max=50  

### ISSUE THREAD

**Issue by ipleten** [jenkinsci/configuration-as-code-plugin#1374]
Latest version of CaSC:
I get an error:

org.yaml.snakeyaml.error.YAMLException: Number of aliases for non-scalar nodes exceeds the specified max=50

We have a pretty big CaSC yaml file with YAML anchors.

From sneakeyaml documentation:
> maxAliasesForCollections | 50 | Integer | Set the maximum amount of aliases allowed for collections.

**Comment by jetersen** [comment]
Would a configurable max be preferable?

**Comment by jetersen** [comment]
@ipleten could you answer my question above?

Feel free to test it with this HPI: https://repo.jenkins-ci.org/incrementals/io/jenkins/configuration-as-code/1.41-rc1079.80b822bfa420/configuration-as-code-1.41-rc1079.80b822bfa420.hpi

**Comment by ipleten** [comment]
Yeah I believe having possibility to adjust value should be useful. Sorry for late answer.

**Comment by jetersen** [comment]
@ipleten could you perhaps share an example of how you use aliases?
As to write a test.

according to #1246 it is not supported.

**Comment by jetersen** [comment]
The fix is included in [v1.41](https://github.com/jenkinsci/configuration-as-code-plugin/releases/tag/configuration-as-code-1.41)
You can add env or property to fix the issue. The exception should lead you to a solution.

You can increase the maximum by setting an environment variable or property\
  ENV: CASC_YAML_MAX_ALIASES="100"
  PROPERTY: -Dcasc.yaml.max.aliases="100"

**Comment by almiroshnich** [comment]
@ipleten wouldn't you mind me also asking to share your use-case of JCasC config with YAML anchors? I suppose you somehow made it work without root elements but rather as the _in-line references_?
