### ISSUE TITLE
JCasC for clamav and sonarquality gate

### ISSUE THREAD

**Issue by KrishnaveniM1017** [jenkinsci/configuration-as-code-plugin#1578]
Hi everyone . i want to configure clamav and sonarquality gate by automated way .i have tried JCasC plugin configuration for that, but i could not get any. plz help me in this.

**Comment by jetersen** [comment]
Have you tried to configure them in Jenkins UI and use the JCasC export?

**Comment by KrishnaveniM1017** [comment]
yes i have tried. There also clamav, sonarqualitygate doesnot show.

**Comment by jetersen** [comment]
If your using the latest version of clamav and sonarqualitygate plugins and they still do not work, than the issue lies with those two plugins. You should go ask the developers of those plugin to follow the Jenkins plugin conventions.
https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/PLUGINS.md
