### ISSUE TITLE
How to install/configure this plugin

### ISSUE THREAD

**Issue by manishbgit** [jenkinsci/configuration-as-code-plugin#290]
Hi - cant find info on how to install/configure this plugin. 
Did search in the plugin manager but did not find..
Pl advise.
(super idea this btw..)
(not sure if this is the right place for this sort of a question..but had to ask)

**Comment by ewelinawilkosz** [comment]
we do understand the documentation needs to be updated - will be solved in #286, so I'm closing this ticket
until it is solved there is a section about that in README.md

As for installation: since we've only released alpha so far, to install the plugin you need to use experimental update center, details here: https://jenkins.io/doc/developer/publishing/releasing-experimental-updates/

**Comment by manishbgit** [comment]
Thx
