### ISSUE TITLE
Ability to configure Oracle User/Password for JDK download 

### ISSUE THREAD

**Issue by odavid** [jenkinsci/configuration-as-code-plugin#30]
```groovy
def jdkInstaller = jenkins.model.Jenkins.instance.getDescriptor(hudson.tools.JDKInstaller)
jdkInstaller.doPostCredential("user", "password")
```

**Comment by ndeloof** [comment]
unfortunately `hudson.tools.JDKInstaller.DescriptorImpl` does not follow any UI binding convention and uses a custom Web method to expose it's configuration (not even setters for groovy scripting)

**Comment by oleg-nenashev** [comment]
@ndeloof @odavid Currently @dwnusbaum is working on detaching JDKInstaller to a standalone plugin, so somebody will be able to update the plugin to make it more API-friendly.

Generally I do not recommend using this tool installer in any production instance, because we cannot guarantee that Oracle does not change there website again like it happened 2 month ago

**Comment by oleg-nenashev** [comment]
FTR https://github.com/jenkinsci/jenkins/pull/3147

**Comment by ndeloof** [comment]
thanks for the note.
I agree with you there's some options that we might not want to support because they should not be used in production, but that's another debate :P

**Comment by odavid** [comment]
Thanks @oleg-nenashev - I understand your point about Oracle changing their site. 
I opened this issue, since I tried to express something that can be done through the UI, but not through the plugin, so I thought it is worth mentioning.

**Comment by ndeloof** [comment]
please report this RFE on https://github.com/jenkinsci/jdk-tool-plugin
