### ISSUE TITLE
Installation error to the Jenkins Docker Image

### ISSUE THREAD

**Issue by WoodProgrammer** [jenkinsci/configuration-as-code-plugin#410]
I'm getting 404 status code while installing to the Docker image. 
Dockerfile is at as below.

FROM jenkins/jenkins:lts
RUN /usr/local/bin/install-plugins.sh configuration-as-code. 

How I can handle this problem ? Please help .

**Comment by casz** [comment]
You have to speciffy where to download from and what version: see https://github.com/jenkinsci/docker#preinstalling-plugins

Configuration-as-code is still only hosted on experimental since it is still alpha so you want to run this following:
`RUN /usr/local/bin/install-plugins.sh configuration-as-code:experimental`

**Comment by casz** [comment]
Please join us on [gitter](https://gitter.im/jenkinsci/configuration-as-code-plugin) chat to ask for assistance
