### ISSUE TITLE
invoke doCheck* for dry-run

### ISSUE THREAD

**Issue by ndeloof** [jenkinsci/configuration-as-code-plugin#540]
we can't apply values to actual components during dry-run, but can at least invoke doCheck methods like web UI does to prevent invalid values being set on `apply`.

**Comment by sladyn98** [comment]
So, If I understand correctly and do correct me I am wrong, we need to invoke the `formValidation doCheckNewSource` method during dry-run so that we can prevent invalid values. https://github.com/jenkinsci/configuration-as-code-plugin/blob/d4ee6e56069edbe85f9dd8ef184b6584e16e0000/plugin/src/main/java/io/jenkins/plugins/casc/BaseConfigurator.java#L345
Refering to the above line I can see a configurator.check() being done if dry run is set. Do we want to then invoke a doCheck on it?

**Comment by timja** [comment]
I think so, but I've never touched this code...

**Comment by sladyn98** [comment]
The problem though is we need a string parameter for the `do-Check` but here context is a configuration object, unless we can obtain the configuration conext as a String ?

**Comment by sladyn98** [comment]
@ndeloof @timja Was the original intention of the issue to create a custom method to run `do-Check()` in `BaseConfiguratior.java`
