### ISSUE TITLE
Redmine plugin not supported

### ISSUE THREAD

**Issue by CondormanFr** [jenkinsci/configuration-as-code-plugin#669]
- Jenkins version : 2.138.3
- CasC plugin [ 1.3 ], redmine :0.21
- Operating system [ Linux Docker]

I try to setup [redmine plugin](https://wiki.jenkins.io/display/JENKINS/Redmine+Plugin) thru my jenkins configuration as Code file but i didn't sucess 
```
unclassified:
  redmineprojectproperty:
    name: "Redmine"
    baseUrl: "https://url.to/redmine/"
    versionNumber: "3.3.1"

```

but I get this error 
```
io.jenkins.plugins.casc.ConfiguratorException: Invalid configuration elements for type class hudson.plugins.redmine.RedmineProjectProperty$DescriptorImpl : baseUrl,name,versionNumber.
Available attributes : 
	at io.jenkins.plugins.casc.BaseConfigurator.handleUnknown(BaseConfigurator.java:363)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:352)
	at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:273)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:338)
	at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:273)
	at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$checkWith$8(ConfigurationAsCode.java:657)
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:620)
```
There is no help in the Jenkins Configuration as Code Reference or schema ...

```
hudson.plugins.redmine.RedmineProjectProperty$DescriptorImpl: {
type: "object",
properties: { }
},
```
Is there a way to set it up ?

**Comment by casz** [comment]
It is using a custom configure which according to JCasc will not work:
https://github.com/jenkinsci/redmine-plugin/blob/71c767662d0cbb33b15e120f5d95d4e71429bf17/src/main/java/hudson/plugins/redmine/RedmineProjectProperty.java#L91

https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/PLUGINS.md

**Comment by CondormanFr** [comment]
OK thank you.

**Comment by marob** [comment]
> It is using a custom configure which according to JCasc will not work:
> https://github.com/jenkinsci/redmine-plugin/blob/71c767662d0cbb33b15e120f5d95d4e71429bf17/src/main/java/hudson/plugins/redmine/RedmineProjectProperty.java#L91
> 
> https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/PLUGINS.md

@jetersen: maybe https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/PLUGINS.md evolved since your comment or I don't really understand it, but it seems Redmine plugin could be compatible with JCasC provided it follows the steps described in the PLUGINS documentation.
If so, an issue should be created in https://github.com/jenkinsci/redmine-plugin to make it JCasC compatible.

**Comment by jetersen** [comment]
@marob the `RedmineProjectProperty` does not follow the Configure convention.
https://github.com/jenkinsci/redmine-plugin/blob/27ba4e65308432c6ec104e96812ebccd8b78d1a1/src/main/java/hudson/plugins/redmine/RedmineProjectProperty.java#L91-L117

**Comment by marob** [comment]
@jetersen I'm new to JCasC and Jenkins plugin development. I don't really see what's wrong in the plugin code. Is it that it uses `bindJSONToList` instead of `bindJSON`?
Is there no way to change the code to make it JCasC-compliant?

N.B.: the code that seems to cause problem doesn't seem very useful as it removes from the list duplicate configurations or those with missing name or url (which should be the responsibility of the person doing the configuration in my opinion).
